# -*- coding: utf-8 -*-
"""Code_Challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSdeBd7-o-1-gH2ngbLuoJ1XJCiZrpOV
"""

#This fucntion is O(1) for both space and time compelexity
#The number of operations or memeory does not grow relative to input data

def sort(width, height, length, mass):

  if width <= 0 or height <= 0 or length <= 0:
    raise ValueError("Dimensions must be greater than 0")

  if mass <= 0:
    raise ValueError("Mass must be greater than 0")

  bulky = False
  heavy = False
  volume = width * height * length

  #Check if >= 20 kg
  if mass >= 20:
    heavy = True

  #Check if volume >= 1 million cm^3
  #Also checks if dimensions >= 150 cm
  if volume >= 1_000_000 or width >= 150 or height >= 150 or length >= 150:
    bulky = True

  if bulky and heavy:
    return "REJECTED"

  elif bulky or heavy:
    return "SPECIAL"

  else:
    return "STANDARD"

# Test Cases
if __name__ == "__main__":

    # STANDARD
    assert sort(10, 10, 10, 1) == "STANDARD"
    assert sort(100, 100, 99, 19.99) == "STANDARD"

    # SPECIAL – heavy only
    assert sort(10, 10, 10, 20) == "SPECIAL"
    assert sort(50, 40, 30, 25) == "SPECIAL"

    # SPECIAL – bulky only (volume)
    assert sort(100, 100, 100, 10) == "SPECIAL"
    assert sort(200, 200, 200, 5) == "SPECIAL"

    # SPECIAL – bulky only (dimension)
    assert sort(150, 10, 10, 5) == "SPECIAL"
    assert sort(200, 20, 30, 5) == "SPECIAL"

    # REJECTED – heavy and bulky
    assert sort(150, 150, 150, 20) == "REJECTED"
    assert sort(100, 100, 100, 25) == "REJECTED"
    assert sort(300, 300, 300, 50) == "REJECTED"
    assert sort(150, 150, 150, 50) == "REJECTED"


    # ValueError Tests
    try:
        sort(0, 10, 10, 5)
        raise AssertionError("Expected ValueError for width = 0")
    except ValueError:
        pass

    try:
        sort(-1, 20, 20, 5)
        raise AssertionError("Expected ValueError for negative width")
    except ValueError:
        pass

    try:
        sort(10, 0, 10, 5)
        raise AssertionError("Expected ValueError for height = 0")
    except ValueError:
        pass

    try:
        sort(10, 10, -5, 5)
        raise AssertionError("Expected ValueError for negative length")
    except ValueError:
        pass

    try:
        sort(10, 10, 10, 0)
        raise AssertionError("Expected ValueError for mass = 0")
    except ValueError:
        pass

    try:
        sort(10, 10, 10, -5)
        raise AssertionError("Expected ValueError for negative mass")
    except ValueError:
        pass

    print("All tests passed!")